#Spring Boot application.yml
#spring boot property to set the active profile
spring:
  profiles:
    #Through the naming of the files Spring Boot is able to detect what profile those .yml files are applied to
    active: FR,cat,dev
#user defined properties to set the fake data source
guru:
  username: ymlSuperuser
  password: ymlDbPassword
  jdbcurl: ymlSomeUrlForDB
